#!/bin/bash

# Manual API Testing Script
# This script helps you test the JWT system manually

echo "🔧 Manual API Testing Script for JWT System"
echo "=========================================="

# Configuration
API_KEY="your-api-key-here"
BASE_URL="http://localhost:8080"

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    if [ $1 -eq 0 ]; then
        echo -e "${GREEN}✅ SUCCESS${NC}"
    else
        echo -e "${RED}❌ FAILED${NC}"
    fi
}

echo ""
echo "📋 Prerequisites:"
echo "1. Start your API server: go run ./cmd/api/ --port=8080"
echo "2. Make sure you have a valid API key in database"
echo "3. Make sure you have curl installed"
echo ""

# Check if server is running
echo "🔍 Checking if server is running..."
curl -s -f -o /dev/null --connect-timeout 5 "$BASE_URL/health" 2>/dev/null
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Server is running${NC}"
else
    echo -e "${RED}❌ Server is not running on $BASE_URL${NC}"
    echo "Please start the server first: go run ./cmd/api/ --port=8080"
    exit 1
fi

echo ""
echo "🧪 MANUAL TESTING GUIDE - JWT Flow"
echo "=================================="

echo ""
echo "📱 TYPICAL USAGE FLOW:"
echo "1. Get Public Token (with API Key)"
echo "2. Use Public Token to Login"
echo "3. Get Private Token from Login response"
echo "4. Use Private Token for protected endpoints"

echo ""
echo "1️⃣ STEP 1: GET PUBLIC TOKEN"
echo "# You need API key to get public token"
echo "# Run: go run jwt_tester.go"
echo "# Copy the PUBLIC token from output"

echo ""
echo "2️⃣ STEP 2: LOGIN with Public Token (get Private Token)"
echo "curl -X POST $BASE_URL/api/v1/public/auth/login \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"X-API-Key: \$API_KEY\" \\"
echo "  -H \"Authorization: Bearer \$PUBLIC_JWT_TOKEN\" \\"
echo "  -d '{\"username\":\"your-username\",\"password\":\"your-password\"}'"
echo "# Response should contain PRIVATE token"

echo ""
echo "3️⃣ STEP 3: USE Private Token for Protected Endpoints"
echo "curl -X GET $BASE_URL/api/v1/private/users/profile \\"
echo "  -H \"X-API-Key: \$API_KEY\" \\"
echo "  -H \"Authorization: Bearer \$PRIVATE_JWT_TOKEN\""

echo ""
echo "4️⃣ SECURITY TESTS:"
echo ""
echo "# Test 1: Try Public Token on Private Endpoint (should fail)"
echo "curl -X GET $BASE_URL/api/v1/private/users/profile \\"
echo "  -H \"X-API-Key: \$API_KEY\" \\"
echo "  -H \"Authorization: Bearer \$PUBLIC_JWT_TOKEN\""
echo "# Expected: Error - public token not valid for private endpoint"
echo ""
echo "# Test 2: Try without API Key (should fail)"
echo "curl -X GET $BASE_URL/api/v1/private/users/profile \\"
echo "  -H \"Authorization: Bearer \$PRIVATE_JWT_TOKEN\""
echo "# Expected: Error - API key required"
echo ""
echo "# Test 3: Try with wrong API Key (should fail)"
echo "curl -X GET $BASE_URL/api/v1/private/users/profile \\"
echo "  -H \"X-API-Key: wrong-api-key\" \\"
echo "  -H \"Authorization: Bearer \$PRIVATE_JWT_TOKEN\""
echo "# Expected: Error - invalid API key"

echo ""
echo "🔑 SAMPLE TOKENS FROM PREVIOUS TEST:"
echo "You can use the tokens generated by: go run jwt_tester.go"

echo ""
echo "🌐 ONLINE JWT DEBUGGER:"
echo "Visit: https://jwt.io/"
echo "Secret: test-secret-key-for-manual-testing"
echo "Algorithm: HS256"

echo ""
echo "📝 TOKEN STRUCTURE DIFFERENCES:"
echo ""
echo "Public JWT Claims:"
echo "{"
echo "  \"api_key_id\": 1,"
echo "  \"api_key_name\": \"test-key\","
echo "  \"iss\": \"go-rest-api\","
echo "  \"sub\": \"public-access\","
echo "  \"exp\": 1234567890"
echo "}"
echo ""
echo "Private JWT Claims:"
echo "{"
echo "  \"api_key_id\": 1,"
echo "  \"api_key_name\": \"test-key\","
echo "  \"user_id\": 999,"
echo "  \"username\": \"testuser\","
echo "  \"email\": \"test@example.com\","
echo "  \"iss\": \"go-rest-api\","
echo "  \"sub\": \"private-access\","
echo "  \"exp\": 1234567890"
echo "}"

echo ""
echo "🚀 QUICK START:"
echo "1. Run: go run jwt_tester.go"
echo "2. Copy the generated tokens"
echo "3. Replace \$API_KEY and \$JWT_TOKEN in curl commands above"
echo "4. Test your endpoints!"

echo ""
echo "💡 TIP: Save this script and make it executable:"
echo "chmod +x manual_test_guide.sh"
echo "./manual_test_guide.sh"
